name: Civic Issues Analytics

on:
  issues:
    types: [opened, edited, closed]
  schedule:
    # Run analytics every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

# Fix for 403 permission error - explicit permissions needed
permissions:
  contents: write      # Allow writing to repository
  issues: write        # Allow commenting on issues
  pull-requests: write # Allow creating PRs if needed

jobs:
  analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Use token with write permissions
        token: ${{ secrets.GITHUB_TOKEN }}
        # Fetch full history for proper git operations
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run analytics
      run: node scripts/analytics.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create analytics summary
      run: node scripts/create-summary.js
      
    - name: Comment on issues with analytics
      if: github.event_name == 'issues'
      run: node scripts/comment-analytics.js ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push analytics results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add analytics/
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Update analytics data - $(date -u +'%Y-%m-%d %H:%M UTC')"
        git push origin HEAD:${{ github.ref }}
